spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ClientsDataApi
      username:                       #Логін для підключення до вашої БД
      password:                       #Пароль для підключення до вашої БД
      authentication-database: admin
      auto-index-creation: true

